export default {
  REQUESTED: 'ZIP_CODE.REQUESTED',
  REQUESTED_SUCCESS: 'ZIP_CODE.REQUESTED_SUCCESS',
  REQUESTED_FAILED: 'ZIP_CODE.REQUESTED_FAILED',
  CHANGE_ZIP_CODE: 'ZIP_CODE.CHANGE_ZIP_CODE',
  ADD_PLACE: 'ZIP_CODE.ADD_PLACE',
  REMOVE_PLACE: 'ZIP_CODE.REMOVE_PLACE',
};
